spring:
  application:
    name: task-tracker-mailsender
  email:
    box: atom44394@gmail.com
    provider: mailgun
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue-name: EMAIL_SENDING_TASKS
  amqp:
    deserialization:
      trust:
        all: true