spring:
  application:
    name: task-tracker-mailsender
  mail:
    sender-email: atom44394@gmail.com
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue-name: EMAIL_SENDING_TASKS